vim.g.mapleader = " " -- Set <Space> as <Leeader>
vim.g.maplocalleader = " " -- Set <Space> as <LocalLeader>

vim.opt.breakindent = true -- Wrapped line repeats indent
vim.opt.clipboard = "unnamedplus" -- Sync Neovim and OS clipboard
vim.opt.completeopt = "menu,menuone,noselect" -- Options for Insert mode completion
vim.opt.expandtab = true -- Use spaces when tab is inserted
vim.opt.hlsearch = false -- Highlight matches with last search pattern
vim.opt.ignorecase = true -- Ignore case in search patterns
vim.opt.number = true -- Print the line numbers
vim.opt.relativenumber = true -- Show relative line numbers
vim.opt.shiftwidth = 4 -- Number of spaces for autoindent
vim.opt.signcolumn = "yes" -- Always display the sign column
vim.opt.smartcase = true -- Do not ignore case when pattern has uppercase
vim.opt.splitbelow = true -- Split new window below current
vim.opt.splitright = true -- Split new window right of current
vim.opt.tabstop = 4 -- Number of spaces tab uses
vim.opt.termguicolors = true -- Enable 24-bit RGB color
vim.opt.wrap = false -- Long lines wrap to the next line
