tap "homebrew/bundle"
tap "homebrew/cask-fonts"

brew "fd"
brew "fish"
brew "fisher"
brew "neovim"
brew "node@20"
brew "nodenv"
brew "pyenv"
brew "python@3.12"
brew "ripgrep"
brew "starship"
brew "tree"
brew "wget"

cask "font-sf-mono"
cask "font-symbols-only-nerd-font"
cask "visual-studio-code"
cask "wezterm"

vscode "asvetliakov.vscode-neovim"
vscode "Catppuccin.catppuccin-vsc"
vscode "dbaeumer.vscode-eslint"
vscode "esbenp.prettier-vscode"
vscode "huacnlee.theme-macos-classic"
vscode "JohnnyMorganz.stylua"
vscode "medo64.render-crlf"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "servicenow.now-vscode"
vscode "streetsidesoftware.code-spell-checker"
vscode "sumneko.lua"
