"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3
final_space = false

#
# First Line
#

[[blocks]]
type = "prompt"
alignment = "left"

# User and Host

[[blocks.segments]]
type = "session"
style = "plain"
foreground = "darkGray"
template = "{{ if .SSHSession }}{{ .UserName }}@{{ .HostName }}{{ end }} "

# Path

[[blocks.segments]]
type = "path"
style = "plain"
foreground = "blue"
template = "{{ .Path }}"

[blocks.segments.properties]
style = "full"

# Git

[[blocks.segments]]
type = "git"
style = "plain"
foreground = "darkGray"
template = """ {{ .HEAD }}\
    {{ if or .Working.Changed .Staging.Changed }}<red>*</>{{ end }}\
    {{ if or (gt .Ahead 0) (gt .Behind 0) }} {{ end }}\
    {{ if gt .Ahead 0 }}<cyan>⇡</>{{ end }}\
    {{ if gt .Behind 0 }}<cyan>⇣</>{{ end }}\
    {{ if gt .StashCount 0 }} <cyan>≡</>{{ end }}"""

[blocks.segments.properties]
fetch_status = true
branch_icon = ""

# Execution Time

[[blocks.segments]]
type = "executiontime"
style = "plain"
foreground = "yellow"
template = " {{ .FormattedMs }}\n"

[blocks.segments.properties]
style = "round"
always_enabled = true

#
# Second Line
#

[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = "status"
style = "plain"
foreground = "magenta"
foreground_templates = ["{{ if gt .Code 0 }}red{{ end }}"]
template = "❯ "

[blocks.segments.properties]
always_enabled = true

#
# Transient Prompt
#

[transient_prompt]
foreground = "magenta"
template = "❯ "
