"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3
final_space = false

#
# First Line
#

[[blocks]]
type = "prompt"
alignment = "left"

# Mode

[[blocks.segments]]
type = "text"
style = "plain"
template = """\
    {{ if eq \"default\" .Env.OMP_BIND_MODE }}<blue>[N]</>{{ end }}\
    {{ if eq \"insert\" .Env.OMP_BIND_MODE }}<green>[I]</>{{ end }}\
    {{ if eq \"replace\" .Env.OMP_BIND_MODE }}<red>[R]</>{{ end }}\
    {{ if eq \"replace_one\" .Env.OMP_BIND_MODE }}<blue>[N]</>{{ end }}\
    {{ if eq \"visual\" .Env.OMP_BIND_MODE }}<magenta>[V]</>{{ end }}\
    """

# User and Host

[[blocks.segments]]
type = "session"
style = "plain"
foreground = "darkGray"
template = " {{ if .SSHSession }}{{ .UserName }}@{{ .HostName }}{{ end }}"

# Path

[[blocks.segments]]
type = "path"
style = "plain"
foreground = "blue"
template = " {{ .Path }}"

[blocks.segments.properties]
style = "full"

# Git

[[blocks.segments]]
type = "git"
style = "plain"
foreground = "darkGray"
template = " {{ .HEAD }}"

[blocks.segments.properties]
branch_icon = ""

# Execution Time

[[blocks.segments]]
type = "executiontime"
style = "plain"
foreground = "yellow"
template = " {{ .FormattedMs }}\n"

[blocks.segments.properties]
style = "round"
always_enabled = true

#
# Second Line
#

[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = "status"
style = "plain"
foreground_templates = [
  "{{ if eq .Env.OMP_BIND_MODE \"default\" }}blue{{ end }}",
  "{{ if eq .Env.OMP_BIND_MODE \"insert\" }}green{{ end }}",
  "{{ if eq .Env.OMP_BIND_MODE \"replace\" }}red{{ end }}",
  "{{ if eq .Env.OMP_BIND_MODE \"replace_one\" }}blue{{ end }}",
  "{{ if eq .Env.OMP_BIND_MODE \"visual\" }}magenta{{ end }}",
]
template = ">>> "

[blocks.segments.properties]
always_enabled = true
