tap "homebrew/bundle"
tap "sst/tap"

brew "bash"
brew "fd"
brew "fish"
brew "fzf"
brew "git"
brew "go"
brew "goimports"
brew "gopls"
brew "jq"
brew "lazygit"
brew "lua-language-server"
brew "markdown-toc"
brew "markdownlint-cli2"
brew "marksman"
brew "mas"
brew "neovim"
brew "node@22"
brew "nodenv"
brew "sst/tap/opencode"
brew "prettier"
brew "pyenv"
brew "python@3.12"
brew "rbenv"
brew "ripgrep"
brew "ruby"
brew "ruby-lsp"
brew "rust-analyzer"
brew "shfmt"
brew "sqlite"
brew "stylua"
brew "taplo"
brew "tree"
brew "wget"
brew "zls"

cask "1password"
cask "1password-cli"
cask "claude-code"
cask "docker-desktop"
cask "font-jetbrains-mono"
cask "font-sf-mono"
cask "font-symbols-only-nerd-font"
cask "ghostty"

mas "1Password for Safari", id: 1569813296

require "socket"
hostname = Socket.gethostname.downcase

if hostname.start_with? "christopher"
  cask "arq"
  cask "dropbox"
  cask "fission"
  cask "powerphotos"
  cask "sf-symbols"

  mas "Audiobook Builder", id: 1437681957
  mas "Developer", id: 640199958
  mas "GarageBand", id: 682658836
  mas "iMovie", id: 408981434
  mas "Keynote", id: 409183694
  mas "Microsoft Excel", id: 462058435
  mas "Microsoft Word", id: 462054704
  mas "Numbers", id: 409203825
  mas "Outread", id: 778846279
  mas "Pages", id: 409201541
  mas "Speedtest", id: 1153157709
  mas "Xcode", id: 497799835
else
  tap "homebrew/services"

  brew "node-build"

  cask "intellij-idea"

  mas "Okta Extension App", id: 1439967473
end
